name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v3
      - name: "🚀 Deploy"
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          BUILD_DIR: ./src
          SLUG: nettle-pay
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
