name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v3
      - name: "🔧 Setup"
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: "📦 Install"
        run: npm install semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec @semantic-release/git @semantic-release/github @semantic-release/release-notes-generator --no-save
      - name: "🔖 Release"
        env:
          # use custom PAT to trigger a workflow for release: [publish] event, see https://github.com/semantic-release/github#github-authentication for more details
          GITHUB_TOKEN: ${{ secrets.READ_AND_WRITE_REPOS_TOKEN }}
        run: npx semantic-release
